### ISSUE TITLE
Convert Snake case to Pascal case

### ISSUE THREAD

**Issue by jatinkumar027** [jatinkumar027/Nourishing-Skills#12]
Definition of done:

1. Clear code should be written.
2. Comments will be really appreciable.
3. Add minimum 2 test cases to test the code.
4. Add you code under Python/Data Structure and Algorithms/<ProgramName.py>

**Comment by Hritik-Verma41** [comment]
assign to me

**Comment by jatinkumar027** [comment]
Done

**Comment by Hritik-Verma41** [comment]
@jatinkumar027 Done please check and merge

**Comment by jatinkumar027** [comment]
Done https://github.com/jatinkumar027/Nourishing-Skills/pull/15#issue-1393315295
