### ISSUE TITLE
Python program to find uncommon words from two Strings

### ISSUE THREAD

**Issue by jatinkumar027** [jatinkumar027/Nourishing-Skills#13]
Definition of done:

1. Clear code should be written.
2. Comments will be really appreciable.
3. Add minimum 2 test cases to test the code.
4. Add you code under Python/Data Structure and Algorithms/<ProgramName.py>
5. Make sure to add the Screenshot of Program Testing in the comment while merging the PR

**Comment by Hritik-Verma41** [comment]
assign this to me

**Comment by jatinkumar027** [comment]
Done

**Comment by Hritik-Verma41** [comment]
@jatinkumar027 added please check
