### ISSUE TITLE
Add Algorithms in Python folder

### ISSUE THREAD

**Issue by jatinkumar027** [jatinkumar027/Nourishing-Skills#2]
Definition of Done:
1. Different Algorithms should be written in python
2. Comments in code (if applicable)

**Comment by Tejas20-03** [comment]
It will be my Pleasure to work on above issue

**Comment by jatinkumar027** [comment]
Sure, Please add your contribution and get it reviewed 😄

**Comment by Hritik-Verma41** [comment]
I want to add the quicksort algorithm

**Comment by jatinkumar027** [comment]
Sure @Hritik-Verma41 please add that

**Comment by Hritik-Verma41** [comment]
Done please check and merge

**Comment by jatinkumar027** [comment]
> Done please check and merge

Merged Successfully.

**Comment by jatinkumar027** [comment]
Closing the General Issue. Moving to specific Issues from now on
