### ISSUE TITLE
Maximum frequency character in String

### ISSUE THREAD

**Issue by jatinkumar027** [jatinkumar027/Nourishing-Skills#23]
Definition of done:

1. Clear code should be written.
2. Comments will be really appreciable.
3. Add minimum 2 test cases to test the code.
4. Add you code under Python/Data Structure and Algorithms/<ProgramName.py>
5. Make sure to add the Screenshot of Program Testing in the comment while merging the PR

**Comment by vihangamarasinghe** [comment]
Is it possible to work on this ?Thanks

**Comment by jatinkumar027** [comment]
sure. Assigning it to you

**Comment by jatinkumar027** [comment]
Merged
