### ISSUE TITLE
Python Program for Merge Sort

### ISSUE THREAD

**Issue by jatinkumar027** [jatinkumar027/Nourishing-Skills#27]
Definition of done:

1. Clear code should be written.
2. Comments will be really appreciable.
3. Add minimum 2 test cases to test the code.
4. Add you code under Python/Data Structure and Algorithms/<ProgramName.py>
5. Make sure to add the Screenshot of Program Testing in the comment while merging the PR

**Comment by ArSin2002** [comment]
can i work on this @jatinkumar027

**Comment by jatinkumar027** [comment]
Sure

**Comment by ArSin2002** [comment]
this task is done . please merge request @jatinkumar027
