### ISSUE TITLE
Python Program for Selection Sort

### ISSUE THREAD

**Issue by jatinkumar027** [jatinkumar027/Nourishing-Skills#28]
Definition of done:

1. Clear code should be written.
2. Comments will be really appreciable.
3. Add minimum 2 test cases to test the code.
4. Add you code under Python/Data Structure and Algorithms/<ProgramName.py>
5. Make sure to add the Screenshot of Program Testing in the comment while merging the PR

**Comment by ashishpetwal** [comment]
Kindly assign this issue to me! I would love to work on it..

**Comment by jatinkumar027** [comment]
done

**Comment by ashishpetwal** [comment]
let me solve
