### ISSUE TITLE
Add a Python program for Bubble Sort Algoritm

### ISSUE THREAD

**Issue by jatinkumar027** [jatinkumar027/Nourishing-Skills#3]
Definition of done:
1. Clear code for Bubble Sort Algoritm in python should be written.
2. Comments will be really appreciable.
3. Add minimum 2 test cases to test the code.
4. Add you code under Python/Data Structure and Algorithms/

**Comment by Vaani-pathariya** [comment]
Hello @jatinkumar027 can i contribute to this one .Please guide how am i supposed to add testcases

**Comment by jatinkumar027** [comment]
Hi @Vaani-pathariya,

Write the algorithm in a function first. After making that function, write two test case with a sample input where you will that function. Print the output.
That's it review the output and see if it matches with the expected result

Sample code:
https://github.com/jatinkumar027/Nourishing-Skills/blob/3d66ee6ea68fe644e4a58e6a7497bd0ff9ef0065/Python/Data%20Structure%20and%20Algorithms/BinarySearch.py

**Comment by Hritik-Verma41** [comment]
Hi @jatinkumar027 can I work on writing two test cases?

**Comment by jatinkumar027** [comment]
I think @Hritik-Verma41, you can see this https://github.com/jatinkumar027/Nourishing-Skills/issues/6#issue-1393302303

**Comment by Hritik-Verma41** [comment]
ok sure

**Comment by Vaani-pathariya** [comment]
> Hi @Vaani-pathariya,
> 
> Write the algorithm in a function first. After making that function, write two test case with a sample input where you will that function. Print the output. That's it review the output and see if it matches with the expected result
> 
> Sample code: https://github.com/jatinkumar027/Nourishing-Skills/blob/3d66ee6ea68fe644e4a58e6a7497bd0ff9ef0065/Python/Data%20Structure%20and%20Algorithms/BinarySearch.py

Ok ,got it ! Thank you

**Comment by jatinkumar027** [comment]
No problem. Please let me know if you are working on this. So that I can assign this to you

**Comment by Vaani-pathariya** [comment]
Yes I am working on this

**Comment by jatinkumar027** [comment]
Great. Assigned to you

**Comment by ArSin2002** [comment]
can is work on the bubble sort algorithm @jatinkumar027 ??
