### ISSUE TITLE
Program for Number of stopping station problem in Python

### ISSUE THREAD

**Issue by jatinkumar027** [jatinkumar027/Nourishing-Skills#34]
Problem:
There are 12 intermediate stations between two places A and B. Find the number of ways in which a train can be made to stop at 4 of these intermediate stations so that no two stopping stations are consecutive?

Definition of done:

1. Clear code should be written.
2. Comments will be really appreciable.
3. Add minimum 2 test cases to test the code.
4. Add you code under Python/Data Structure and Algorithms/<ProgramName.py>
5. Make sure to add the Screenshot of Program Testing in the comment while merging the PR

**Comment by Tanmay0808** [comment]
Hi, i have created a PR for the solution. Please review it at your earliest convenience.

**Comment by jatinkumar027** [comment]
merged successfully. 😊 Thanks @Tanmay0808
