### ISSUE TITLE
Python Program for Find sum of even factors of a number

### ISSUE THREAD

**Issue by jatinkumar027** [jatinkumar027/Nourishing-Skills#36]
Definition of done:

1. Clear code should be written.
2. Comments will be really appreciable.
3. Add minimum 2 test cases to test the code.
4. Add you code under Python/Data Structure and Algorithms/<ProgramName.py>
5. Make sure to add the Screenshot of Program Testing in the comment while merging the PR

**Comment by Vaani-pathariya** [comment]
Can i contribute to this one ?

**Comment by jatinkumar027** [comment]
Okay assigning it to you
