### ISSUE TITLE
Python program to find the most occurring character and its count

### ISSUE THREAD

**Issue by jatinkumar027** [jatinkumar027/Nourishing-Skills#37]
Definition of done:

1. Clear code should be written.
2. Comments will be really appreciable.
3. Add minimum 2 test cases to test the code.
4. Add you code under Python/Data Structure and Algorithms/<ProgramName.py>
5. Make sure to add the Screenshot of Program Testing in the comment while merging the PR

**Comment by Tanmay0808** [comment]
Hi, can i pick up this? if yes please assign it to me.

**Comment by jatinkumar027** [comment]
Sure. done

**Comment by jatinkumar027** [comment]
Merged 😊
