### ISSUE TITLE
Add a program to Remove duplicates from a sentence in python

### ISSUE THREAD

**Issue by jatinkumar027** [jatinkumar027/Nourishing-Skills#4]
Definition of done:

1. Clear code should be written.
2. Comments will be really appreciable.
3. Add minimum 2 test cases to test the code.
4. Add you code under Python/Data Structure and Algorithms/

**Comment by nayanapardhekar** [comment]
I would like to contribute to this issue, May I please?

**Comment by jatinkumar027** [comment]
Sure @nayanapardhekar Please go on
