### ISSUE TITLE
Python Program for Tower of Hanoi

### ISSUE THREAD

**Issue by jatinkumar027** [jatinkumar027/Nourishing-Skills#40]
Tower of Hanoi is a mathematical puzzle where we have three rods and n disks. The objective of the puzzle is to move the entire stack to another rod, obeying the following simple rules: 
1) Only one disk can be moved at a time. 
2) Each move consists of taking the upper disk from one of the stacks and placing it on top of another stack i.e. a disk can only be moved if it is the uppermost disk on a stack. 
3) No disk may be placed on top of a smaller disk.
Note: Transferring the top n-1 disks from source rod to Auxiliary rod can again be thought of as a fresh problem and can be solved in the same manner.

Definition of done:

1. Clear code should be written.
2. Comments will be really appreciable.
3. Add minimum 2 test cases to test the code.
4. Add you code under Python/Data Structure and Algorithms/<ProgramName.py>
5. Make sure to add the Screenshot of Program Testing in the comment while merging the PR

**Comment by Tanmay0808** [comment]
Hi, i am working on this one as well, please assign it to me.

**Comment by jatinkumar027** [comment]
Okay. sure

**Comment by jatinkumar027** [comment]
Merged https://github.com/jatinkumar027/Nourishing-Skills/pull/43#issue-1393401237
