### ISSUE TITLE
Python Program for Maximum height when coins are arranged in a triangle

### ISSUE THREAD

**Issue by jatinkumar027** [jatinkumar027/Nourishing-Skills#42]
Problem:
We have N coins which need to arrange in form of a triangle, i.e. first row will have 1 coin, second row will have 2 coins and so on, we need to tell maximum height which we can achieve by using these N coins.

Definition of done:

1. Clear code should be written.
2. Comments will be really appreciable.
3. Add minimum 2 test cases to test the code.
4. Add you code under Python/Data Structure and Algorithms/<ProgramName.py>
5. Make sure to add the Screenshot of Program Testing in the comment while merging the PR

**Comment by Tanmay0808** [comment]
Please assign it to me, good problems.

**Comment by jatinkumar027** [comment]
Done.

**Comment by jatinkumar027** [comment]
Merged https://github.com/jatinkumar027/Nourishing-Skills/pull/45#issue-1393404863
