### ISSUE TITLE
Check if Binary representation is Palindrome in Python

### ISSUE THREAD

**Issue by jatinkumar027** [jatinkumar027/Nourishing-Skills#49]
Problem:

Given an integer ‘n’, write a Python function that returns true if binary representation of x is palindrome else return false. Examples:

Input : n = 9
Output : True
Binary representation of n=9 is 1001 which 
is palindrome as well.

Input : n = 10
Output : False
Binary representation of n=10 is 1010 which 
is not palindrome.

Definition of done:

1. Clear code should be written.
2. Comments will be really appreciable.
3. Add minimum 2 test cases to test the code.
4. Add you code under Python/Data Structure and Algorithms/<ProgramName.py>
5. Make sure to add the Screenshot of Program Testing in the comment while merging the PR

**Comment by ananya-1112** [comment]
I would like to work on this

**Comment by jatinkumar027** [comment]
Sure, assigned to you
