### ISSUE TITLE
Python Program to Find sum of odd factors of a number

### ISSUE THREAD

**Issue by jatinkumar027** [jatinkumar027/Nourishing-Skills#50]
Problem:
Given a number n, the task is to find the odd factor sum. Examples:

Input : n = 30
Output : 24
Odd dividers sum 1 + 3 + 5 + 15 = 24 

Input : 18
Output : 13
Odd dividers sum 1 + 3 + 9 = 13

Definition of done:

1. Clear code should be written.
2. Comments will be really appreciable.
3. Add minimum 2 test cases to test the code.
4. Add you code under Python/Data Structure and Algorithms/<ProgramName.py>
5. Make sure to add the Screenshot of Program Testing in the comment while merging the PR

**Comment by redromnon** [comment]
Hello there! I'm interested to work on this.

**Comment by jatinkumar027** [comment]
Okay. Assigned to you
