### ISSUE TITLE
Python Program for Heap Sort

### ISSUE THREAD

**Issue by jatinkumar027** [jatinkumar027/Nourishing-Skills#53]
Definition of done:

1. Clear code should be written.
2. Comments will be really appreciable.
3. Add minimum 2 test cases to test the code.
4. Add you code under Python/Data Structure and Algorithms/<ProgramName.py>
5. Make sure to add the Screenshot of Program Testing in the comment while merging the PR

**Comment by tsari02** [comment]
Please assign this issue to me.

**Comment by PriyanshuAhlawat** [comment]
@jatinkumar027 I will like to work on this, pls assign

**Comment by tsari02** [comment]
I already submitted the PR for this.

**Comment by jatinkumar027** [comment]
@PriyanshuAhlawat you can pick a new issue. Be sure to comment in that first
