### ISSUE TITLE
Python Program to check Armstrong Number

### ISSUE THREAD

**Issue by jatinkumar027** [jatinkumar027/Nourishing-Skills#6]
Definition of done:

1. Clear code should be written.
2. Comments will be really appreciable.
3. Add minimum 2 test cases to test the code.
4. Add you code under Python/Data Structure and Algorithms/<ProgramName.py>

**Comment by Tejas20-03** [comment]
Please Assign it to me @jatinkumar027

**Comment by Hritik-Verma41** [comment]
will work on this

**Comment by jatinkumar027** [comment]
@Hritik-Verma41 See if you can do this https://github.com/jatinkumar027/Nourishing-Skills/issues/8#issue-1393303904

**Comment by jatinkumar027** [comment]
@Tejas20-03 you can go on with this

**Comment by Tejas20-03** [comment]
@jatinkumar027 Do I have to write for Bubble sort or Armstrong Number?
I'm little bit confused

**Comment by jatinkumar027** [comment]
You can continue with Armstrong Number

**Comment by Tejas20-03** [comment]
Ohk Thanks for Clearing

**Comment by Hritik-Verma41** [comment]
@jatinkumar027 added the armstrong program in python please check and merge

**Comment by jatinkumar027** [comment]
Merged @Hritik-Verma41 . @Tejas20-03 please address the comment in PR and then will merge you request too

**Comment by jatinkumar027** [comment]
> Merged @Hritik-Verma41 . @Tejas20-03 please address the comment in PR and then will merge your request too
