### ISSUE TITLE
Count the Number of matching characters in a pair of string in Python

### ISSUE THREAD

**Issue by jatinkumar027** [jatinkumar027/Nourishing-Skills#8]
Definition of done:

1. Clear code should be written.
2. Comments will be really appreciable.
3. Add minimum 2 test cases to test the code.
4. Add you code under Python/Data Structure and Algorithms/<ProgramName.py>

**Comment by PriyanshuAhlawat** [comment]
@jatinkumar027 I will like to work on this, pls assign

**Comment by Hritik-Verma41** [comment]
I will work on this

**Comment by Hritik-Verma41** [comment]
Also please add the hacktober tag

**Comment by jatinkumar027** [comment]
@Hritik-Verma41 Let me create another issue and make sure to comment in that. 
Comment here https://github.com/jatinkumar027/Nourishing-Skills/issues/12#issue-1393309883

Assigning the current task to @PriyanshuAhlawat

**Comment by jatinkumar027** [comment]
@PriyanshuAhlawat are you working on this?

**Comment by PriyanshuAhlawat** [comment]
@jatinkumar027 made the pr, sorry for the delay
