### ISSUE TITLE
Program to accept the strings which contains all vowels

### ISSUE THREAD

**Issue by jatinkumar027** [jatinkumar027/Nourishing-Skills#9]
Definition of done:

1. Clear code should be written.
2. Comments will be really appreciable.
3. Add minimum 2 test cases to test the code.
4. Add you code under Python/Data Structure and Algorithms/<ProgramName.py>

**Comment by Kunal-Garg-12** [comment]
Please assign this to me

**Comment by jatinkumar027** [comment]
Done

**Comment by ArSin2002** [comment]
can i work on this @jatinkumar027 ???

**Comment by jatinkumar027** [comment]
The issue is closed @ArSin2002 you can pick another Issue
